### ISSUE TITLE
We need a way to optionally specify base URL of (at least) the profile server

### ISSUE THREAD

**Issue by ddotlic** [barchart/marketdata-api-js#2]
For the case where the library is used/hosted in the server not managed by Barchart, we should not use the (hardcoded) relative URL `proxies/instruments` to fetch data. The base URL should be configurable.

Please see [related discussion here](https://github.com/barchart/marketdata-ui-js/issues/41).

Note that the setting has been added to the chart component, though it's not used there. We might opt to configure it only there and just pass it on to the API, or to configure the API separately.

@bryaningl3 let me know what you think.

**Comment by bryaningl3** [comment]
The idea of a "proxy" script has been deprecated. I'm making a change that will retrieve profiles, in one of two ways:

1. HTTP request to CORS-enabled server, or
1. Single snapshot request to JERQ (i.e. GO=IBM s)

Stay tuned.

**Comment by ddotlic** [comment]
This issue is obsolete.
